### PR TITLE
Final mix

### PR DESCRIPTION
**Pull request by bruser2000**

### CODE REVIEW

**Comment by tmray** [comment]
We don't merge branches

**Comment by bruser2000** [comment]
Ha! I couldn’t get anything to work. Was just trying to load the latest version of the song to Ardour with no luck 👎🏼👎🏼On Aug 16, 2023, at 12:25 PM, Tom Ray ***@***.***> wrote:﻿
We don't merge branches

**Comment by tmray** [comment]
Yeah, I'll go over it with you :)

Tom Ray

Website & Podcast - https://www.tomrayswebsite.com
Music - http://www.lorenzosmusic.com

**Comment by bruser2000** [comment]
Thanks….I was even working off the notes I took, and still had issues. 🤷🏻‍♂️On Aug 16, 2023, at 2:52 PM, Tom Ray ***@***.***> wrote:﻿
Yeah, I'll go over it with you :)



Tom Ray



Website & Podcast - https://www.tomrayswebsite.com

Music - http://www.lorenzosmusic.com

**Pull request closed without merging**
